# Generated by Django 4.2.7 on 2025-06-25 22:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Logo du client (upload automatique vers Cloudinary)', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='client',
            name='logo_white',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Version blanche du logo (upload automatique vers Cloudinary)', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(help_text='Image principale du projet (upload automatique vers Cloudinary)', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Miniature du projet (générée automatiquement si vide)', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=cloudinary.models.CloudinaryField(help_text='Image de galerie (upload automatique vers Cloudinary)', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='projecttestimonial',
            name='client_photo',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Photo du client (upload automatique vers Cloudinary)', max_length=255, null=True, verbose_name='image'),
        ),
    ]
