# Generated by Django 4.2.7 on 2025-06-26 09:22

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_update_to_cloudinary_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="logo_cloudinary_public_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="client",
            name="logo_large",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="client_logo_large"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="logo_thumbnail",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="client_logo_thumbnail",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="logo_white_cloudinary_public_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="client",
            name="logo_white_large",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="client_logo_white_large",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="logo_white_thumbnail",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="client_logo_white_thumbnail",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="featured_image_cloudinary_public_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="project",
            name="featured_image_large",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="project_featured_image_large",
            ),
        ),
        migrations.AddField(
            model_name="projectimage",
            name="image_cloudinary_public_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="projectimage",
            name="image_large",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="project_gallery_image_large",
            ),
        ),
        migrations.AddField(
            model_name="projectimage",
            name="image_thumbnail",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="project_gallery_image_thumbnail",
            ),
        ),
        migrations.AddField(
            model_name="projecttestimonial",
            name="client_photo_cloudinary_public_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="projecttestimonial",
            name="client_photo_large",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="testimonial_client_photo_large",
            ),
        ),
        migrations.AddField(
            model_name="projecttestimonial",
            name="client_photo_thumbnail",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="testimonial_client_photo_thumbnail",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="logo",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="client_logo"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="logo_white",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="client_logo_white"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="featured_image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="project_featured_image",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="thumbnail",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="project_featured_image_thumbnail",
            ),
        ),
        migrations.AlterField(
            model_name="projectimage",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="project_gallery_image",
            ),
        ),
        migrations.AlterField(
            model_name="projecttestimonial",
            name="client_photo",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="testimonial_client_photo",
            ),
        ),
    ]
