# Generated by Django 4.2.7 on 2025-06-26 12:33

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0003_client_logo_cloudinary_public_id_client_logo_large_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True,
                help_text="Contenu détaillé du case study",
                verbose_name="Content",
            ),
        ),
        migrations.AlterField(
            model_name="projectcategory",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="projectimage",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, verbose_name="Description"
            ),
        ),
    ]
