# Generated by Django 4.2.7 on 2025-06-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_client_description_alter_project_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AddField(
            model_name='client',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text="Ordre d'affichage du client dans la section logos"),
        ),
    ]
